# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/say_hi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='io/say_hi.proto',
  package='io',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0fio/say_hi.proto\x12\x02io\":\n\x05SayHi\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x11\n\tsomething\x18\x02 \x02(\t\x12\x12\n\nextra_info\x18\x03 \x01(\t')
)




_SAYHI = _descriptor.Descriptor(
  name='SayHi',
  full_name='io.SayHi',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='io.SayHi.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='something', full_name='io.SayHi.something', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extra_info', full_name='io.SayHi.extra_info', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['SayHi'] = _SAYHI
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SayHi = _reflection.GeneratedProtocolMessageType('SayHi', (_message.Message,), {
  'DESCRIPTOR' : _SAYHI,
  '__module__' : 'io.say_hi_pb2'
  # @@protoc_insertion_point(class_scope:io.SayHi)
  })
_sym_db.RegisterMessage(SayHi)


# @@protoc_insertion_point(module_scope)
